export const USER_LOGIN_REQUEST = 'currentUser/USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'currentUser/USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'currentUser/USER_LOGIN_FAILURE'

export const USER_FETCH_REQUEST = 'currentUser/USER_FETCH_REQUEST'
export const USER_FETCH_SUCCESS = 'currentUser/USER_FETCH_SUCCESS'
export const USER_FETCH_FAILURE = 'currentUser/USER_FETCH_FAILURE'

export const USER_LOGOUT_REQUEST = 'currentUser/USER_LOGOUT_REQUEST'
export const USER_LOGOUT_SUCCESS = 'currentUser/USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAILURE = 'currentUser/USER_LOGOUT_FAILURE'

export const USER_SIGNUP_REQUEST = 'currentUser/USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'currentUser/USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAILURE = 'currentUser/USER_SIGNUP_FAILURE'

export const USER_UPDATE_REQUEST = 'currentUser/USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'currentUser/USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAILURE = 'currentUser/USER_UPDATE_FAILURE'

export const USER_COMPLETE_PROFILE_REQUEST = 'currentUser/USER_COMPLETE_PROFILE_REQUEST'
export const USER_COMPLETE_PROFILE_SUCCESS = 'currentUser/USER_COMPLETE_PROFILE_SUCCESS'
export const USER_COMPLETE_PROFILE_FAILURE = 'currentUser/USER_COMPLETE_PROFILE_FAILURE'

export const USER_CHANGE_PASWORD_REQUEST = 'currentUser/USER_CHANGE_PASWORD_REQUEST'
export const USER_CHANGE_PASWORD_SUCCESS = 'currentUser/USER_CHANGE_PASWORD_SUCCESS'
export const USER_CHANGE_PASWORD_FAILURE = 'currentUser/USER_CHANGE_PASWORD_FAILURE'

export const EDIT_USER_REQUEST = 'currentUser/currentUser/EDIT_USER_REQUEST'
export const EDIT_USER_SUCCESS = 'currentUser/EDIT_USER_SUCCESS'
export const EDIT_USER_FAILURE = 'currentUser/EDIT_USER_FAILURE'

export const USER_QR_CODE_IMAGE_REQUEST = 'currentUser/USER_QR_CODE_IMAGE_REQUEST'
export const USER_QR_CODE_IMAGE_SUCCESS = 'currentUser/USER_QR_CODE_IMAGE_SUCCESS'
export const USER_QR_CODE_IMAGE_FAILURE = 'currentUser/USER_QR_CODE_IMAGE_FAILURE'

export const INVITATION_SIGNUP_REQUEST = 'currentUser/INVITATION_SIGNUP_REQUEST'
export const INVITATION_SIGNUP_SUCCESS = 'currentUser/INVITATION_SIGNUP_SUCCESS'
export const INVITATION_SIGNUP_FAILURE = 'currentUser/INVITATION_SIGNUP_FAILURE'

export const ACTIVE_USER_REQUEST = 'currentUser/ACTIVE_USER_REQUEST'
export const ACTIVE_USER_SUCCESS = 'currentUser/ACTIVE_USER_SUCCESS'
export const ACTIVE_USER_FAILURE = 'currentUser/ACTIVE_USER_FAILURE'

export const REQUEST_DEACTIVE_USER__REQUEST = 'currentUser/REQUEST_DEACTIVE_USER__REQUEST'
export const REQUEST_DEACTIVE_USER__SUCCESS = 'currentUser/REQUEST_DEACTIVE_USER__SUCCESS'
export const REQUEST_DEACTIVE_USER__FAILURE = 'currentUser/REQUEST_DEACTIVE_USER__FAILURE'

export const RESET_PASSWORD_REQUEST = 'currentUser/RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'currentUser/RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'currentUser/RESET_PASSWORD_FAILURE'

export const RESET_PASSWORD_TOKEN_REQUEST = 'currentUser/RESET_PASSWORD_TOKEN_REQUEST'
export const RESET_PASSWORD_TOKEN_SUCCESS = 'currentUser/RESET_PASSWORD_TOKEN_SUCCESS'
export const RESET_PASSWORD_TOKEN_FAILURE = 'currentUser/RESET_PASSWORD_TOKEN_FAILURE'

export const USER_UPDATE_FIELD_VALUE = 'currentUser/USER_UPDATE_FIELD_VALUE'
export const SET_DEFAULT_USER_DATA = 'currentUser/SET_DEFAULT_USER_DATA'

export const COPMANY_UPDATE_INFO_REQUEST = 'currentUser/COPMANY_UPDATE_INFO_REQUEST'
export const COPMANY_UPDATE_INFO_SUCCESS = 'currentUser/COPMANY_UPDATE_INFO_SUCCESS'
export const COPMANY_UPDATE_INFO_FAILURE = 'currentUser/COPMANY_UPDATE_INFO_FAILURE'

export const COMPANY_UPDATE_SETTINGS_REQUEST = 'currentUser/COMPANY_UPDATE_SETTINGS_REQUEST'
export const COMPANY_UPDATE_SETTINGS_SUCCESS = 'currentUser/COMPANY_UPDATE_SETTINGS_SUCCESS'
export const COMPANY_UPDATE_SETTINGS_FAILURE = 'currentUser/COMPANY_UPDATE_SETTINGS_FAILURE'

export const UPLOAD_COMPANY_LOGO_REQUEST = 'currentUser/UPLOAD_COMPANY_LOGO_REQUEST'
export const UPLOAD_COMPANY_LOGO_SUCCESS = 'currentUser/UPLOAD_COMPANY_LOGO_SUCCESS'
export const UPLOAD_COMPANY_LOGO_FAILURE = 'currentUser/UPLOAD_COMPANY_LOGO_FAILURE'

export const UPLOAD_CURRENT_USER_AVATAR_REQUEST = 'currentUser/UPLOAD_CURRENT_USER_AVATAR_REQUEST'
export const UPLOAD_CURRENT_USER_AVATAR_SUCCESS = 'currentUser/UPLOAD_CURRENT_USER_AVATAR_SUCCESS'
export const UPLOAD_CURRENT_USER_AVATAR_FAILURE = 'currentUser/UPLOAD_CURRENT_USER_AVATAR_FAILURE'

export const EDIT_TEAM_REQUEST = 'currentUser/EDIT_TEAM_REQUEST'
export const EDIT_TEAM_SUCCESS = 'currentUser/EDIT_TEAM_SUCCESS'
export const EDIT_TEAM_FAILURE = 'currentUser/EDIT_TEAM_FAILURE'

export const UPLOAD_USER_AVATAR_REQUEST = 'currentUser/UPLOAD_USER_AVATAR_REQUEST'
export const UPLOAD_USER_AVATAR_SUCCESS = 'currentUser/UPLOAD_USER_AVATAR_SUCCESS'
export const UPLOAD_USER_AVATAR_FAILURE = 'currentUser/UPLOAD_USER_AVATAR_FAILURE'
