export const COMMON_UPDATE_FIELD_VALUE = 'common/COMMON_UPDATE_FIELD_VALUE'
export const WIZARD_UPDATE_FIELD_VALUE = 'common/WIZARD_UPDATE_FIELD_VALUE'
export const SET_DEFAULT_COMMON_DATA = 'common/SET_DEFAULT_COMMON_DATA'

export const COUNTRY_LOOKUP_LIST_REQUEST = 'common/COUNTRY_LOOKUP_LIST_REQUEST'
export const COUNTRY_LOOKUP_LIST_SUCCESS = 'common/COUNTRY_LOOKUP_LIST_SUCCESS'
export const COUNTRY_LOOKUP_LIST_FAILURE = 'common/COUNTRY_LOOKUP_LIST_FAILURE'

export const STATE_LOOKUP_LIST_REQUEST = 'common/STATE_LOOKUP_LIST_REQUEST'
export const STATE_LOOKUP_LIST_SUCCESS = 'common/STATE_LOOKUP_LIST_SUCCESS'
export const STATE_LOOKUP_LIST_FAILURE = 'common/STATE_LOOKUP_LIST_FAILURE'

export const HOUSING_TYPES_LOOKUP_LIST_REQUEST = 'common/HOUSING_TYPES_LOOKUP_LIST_REQUEST'
export const HOUSING_TYPES_LOOKUP_LIST_SUCCESS = 'common/HOUSING_TYPES_LOOKUP_LIST_SUCCESS'
export const HOUSING_TYPES_LOOKUP_LIST_FAILURE = 'common/HOUSING_TYPES_LOOKUP_LIST_FAILURE'

export const LOCATION_LOOKUP_LIST_REQUEST = 'common/LOCATION_LOOKUP_LIST_REQUEST'
export const LOCATION_LOOKUP_LIST_SUCCESS = 'common/LOCATION_LOOKUP_LIST_SUCCESS'
export const LOCATION_LOOKUP_LIST_FAILURE = 'common/LOCATION_LOOKUP_LIST_FAILURE'

export const ROOM_TYPES_LOOKUP_LIST_REQUEST = 'common/ROOM_TYPES_LOOKUP_LIST_REQUEST'
export const ROOM_TYPES_LOOKUP_LIST_SUCCESS = 'common/ROOM_TYPES_LOOKUP_LIST_SUCCESS'
export const ROOM_TYPES_LOOKUP_LIST_FAILURE = 'common/ROOM_TYPES_LOOKUP_LIST_FAILURE'

export const SHOW_SNACKBAR_NOTIFICATION = 'common/SHOW_SNACKBAR_NOTIFICATION'

export const GET_METRICS_REQUEST = 'common/GET_METRICS_REQUEST'
export const GET_METRICS_SUCCESS = 'common/GET_METRICS_SUCCESS'
export const GET_METRICS_FAILURE = 'common/GET_METRICS_FAILURE'

export const PERMISSION_LOOKUP_LIST_REQUEST = 'common/PERMISSION_LOOKUP_LIST_REQUEST'
export const PERMISSION_LOOKUP_LIST_SUCCESS = 'common/PERMISSION_LOOKUP_LIST_SUCCESS'
export const PERMISSION_LOOKUP_LIST_FAILURE = 'common/PERMISSION_LOOKUP_LIST_FAILURE'

export const ROLE_LOOKUP_LIST_REQUEST = 'common/ROLE_LOOKUP_LIST_REQUEST'
export const ROLE_LOOKUP_LIST_SUCCESS = 'common/ROLE_LOOKUP_LIST_SUCCESS'
export const ROLE_LOOKUP_LIST_FAILURE = 'common/ROLE_LOOKUP_LIST_FAILURE'
