export const ADD_USER_REQUEST = 'user/ADD_USER_REQUEST'
export const ADD_USER_SUCCESS = 'user/ADD_USER_SUCCESS'
export const ADD_USER_FAILURE = 'user/ADD_USER_FAILURE'

export const EDIT_USER_REQUEST = 'user/EDIT_USER_REQUEST'
export const EDIT_USER_SUCCESS = 'user/EDIT_USER_SUCCESS'
export const EDIT_USER_FAILURE = 'user/EDIT_USER_FAILURE'

export const DELETE_USER_REQUEST = 'user/DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'user/DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'user/DELETE_USER_FAILURE'

export const VIEW_USER_REQUEST = 'user/VIEW_USER_REQUEST'
export const VIEW_USER_SUCCESS = 'user/VIEW_USER_SUCCESS'
export const VIEW_USER_FAILURE = 'user/VIEW_USER_FAILURE'

export const USER_LIST_REQUEST = 'user/USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'user/USER_LIST_SUCCESS'
export const USER_LIST_FAILURE = 'user/USER_LIST_FAILURE'
export const USER_UPDATE_FIELD_VALUE = 'user/USER_UPDATE_FIELD_VALUE'
export const SET_DEFAULT_USER_DATA = 'user/SET_DEFAULT_USER_DATA'

export const GET_REPORTING_DATA_REQUEST = 'user/GET_REPORTING_DATA_REQUEST'
export const GET_REPORTING_DATA_SUCCESS = 'user/GET_REPORTING_DATA_SUCCESS'
export const GET_REPORTING_DATA_FAILURE = 'user/GET_REPORTING_DATA_FAILURE'
export const SET_REPORTING_INIT_DATA = 'user/SET_REPORTING_INIT_DATA'

export const IMPORT_USERS_REQUEST = 'user/IMPORT_USERS_REQUEST'
export const IMPORT_USERS_SUCCESS = 'user/IMPORT_USERS_SUCCESS'
export const IMPORT_USERS_FAILURE = 'user/IMPORT_USERS_FAILURE'

export const INVITE_USER_REQUEST = 'user/INVITE_USER_REQUEST'
export const INVITE_USER_SUCCESS = 'user/INVITE_USER_SUCCESS'
export const INVITE_USER_FAILURE = 'user/INVITE_USER_FAILURE'

export const USER_LOOKUP_LIST_REQUEST = 'user/USER_LOOKUP_LIST_REQUEST'
export const USER_LOOKUP_LIST_SUCCESS = 'user/USER_LOOKUP_LIST_SUCCESS'
export const USER_LOOKUP_LIST_FAILURE = 'user/USER_LOOKUP_LIST_FAILURE'

export const UPLOAD_USER_AVATAR_REQUEST = 'user/UPLOAD_USER_AVATAR_REQUEST'
export const UPLOAD_USER_AVATAR_SUCCESS = 'user/UPLOAD_USER_AVATAR_SUCCESS'
export const UPLOAD_USER_AVATAR_FAILURE = 'user/UPLOAD_USER_AVATAR_FAILURE'

export const GET_ADMIN_LIST_REQUEST = 'user/GET_ADMIN_LIST_REQUEST'
export const GET_ADMIN_LIST_SUCCESS = 'user/GET_ADMIN_LIST_SUCCESS'
export const GET_ADMIN_LIST_FAILURE = 'user/GET_ADMIN_LIST_FAILURE'

export const ADD_ADMIN_REQUEST = 'user/ADD_ADMIN_REQUEST'
export const ADD_ADMIN_SUCCESS = 'user/ADD_ADMIN_SUCCESS'
export const ADD_ADMIN_FAILURE = 'user/ADD_ADMIN_FAILURE'

export const USER_SEARCH_REQUEST = 'USER_SEARCH_REQUEST'
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS'
export const USER_SEARCH_FAILURE = 'USER_SEARCH_FAILURE'
