export const ACTIVITY_BY_KEY_REQUEST = 'activity/ACTIVITY_BY_KEY_REQUEST'
export const ACTIVITY_BY_KEY_SUCCESS = 'activity/ACTIVITY_BY_KEY_SUCCESS'
export const ACTIVITY_BY_KEY_FAILURE = 'activity/ACTIVITY_BY_KEY_FAILURE'

export const ACTIVITY_DELETE_BY_KEY_REQUEST = 'activity/ACTIVITY_DELETE_BY_KEY_REQUEST'
export const ACTIVITY_DELETE_BY_KEY_SUCCESS = 'activity/ACTIVITY_DELETE_BY_KEY_SUCCESS'
export const ACTIVITY_DELETE_BY_KEY_FAILURE = 'activity/ACTIVITY_DELETE_BY_KEY_FAILURE'
