export const TENANT_LIST_REQUEST = 'tenant/TENANT_LIST_REQUEST'
export const TENANT_LIST_SUCCESS = 'tenant/TENANT_LIST_SUCCESS'
export const TENANT_LIST_FAILURE = 'tenant/TENANT_LIST_FAILURE'

export const TENANT_ALL_LIST_REQUEST = 'tenant/TENANT_ALL_LIST_REQUEST'
export const TENANT_ALL_LIST_SUCCESS = 'tenant/TENANT_ALL_LIST_SUCCESS'
export const TENANT_ALL_LIST_FAILURE = 'tenant/TENANT_ALL_LIST_FAILURE'

export const TENANT_SEARCH_REQUEST = 'TENANT_SEARCH_REQUEST'
export const TENANT_SEARCH_SUCCESS = 'TENANT_SEARCH_SUCCESS'
export const TENANT_SEARCH_FAILURE = 'TENANT_SEARCH_FAILURE'

export const LEASE_LIST_REQUEST = 'tenant/LEASE_LIST_REQUEST'
export const LEASE_LIST_SUCCESS = 'tenant/LEASE_LIST_SUCCESS'
export const LEASE_LIST_FAILURE = 'tenant/LEASE_LIST_FAILURE'

export const ADD_TENANT_REQUEST = 'tenant/ADD_TENANT_REQUEST'
export const ADD_TENANT_SUCCESS = 'tenant/ADD_TENANT_SUCCESS'
export const ADD_TENANT_FAILURE = 'tenant/ADD_TENANT_FAILURE'

export const VIEW_TENANT_REQUEST = 'tenant/VIEW_TENANT_REQUEST'
export const VIEW_TENANT_SUCCESS = 'tenant/VIEW_TENANT_SUCCESS'
export const VIEW_TENANT_FAILURE = 'tenant/VIEW_TENANT_FAILURE'

export const UPDATE_TENANT_REQUEST = 'tenant/UPDATE_TENANT_REQUEST'
export const UPDATE_TENANT_SUCCESS = 'tenant/UPDATE_TENANT_SUCCESS'
export const UPDATE_TENANT_FAILURE = 'tenant/UPDATE_TENANT_FAILURE'

export const DELETE_TENANT_REQUEST = 'tenant/DELETE_TENANT_REQUEST'
export const DELETE_TENANT_SUCCESS = 'tenant/DELETE_TENANT_SUCCESS'
export const DELETE_TENANT_FAILURE = 'tenant/DELETE_TENANT_FAILURE'

export const PROPERTY_LIST_REQUEST = 'tenant/PROPERTY_LIST_REQUEST'
export const PROPERTY_LIST_SUCCESS = 'tenant/PROPERTY_LIST_SUCCESS'
export const PROPERTY_LIST_FAILURE = 'tenant/PROPERTY_LIST_FAILURE'

export const ADD_PROPERTY_REQUEST = 'tenant/ADD_PROPERTY_REQUEST'
export const ADD_PROPERTY_SUCCESS = 'tenant/ADD_PROPERTY_SUCCESS'
export const ADD_PROPERTY_FAILURE = 'tenant/PROPERTY_LIST_FAILURE'

export const UNIT_LIST_REQUEST = 'tenant/UNIT_LIST_REQUEST'
export const UNIT_LIST_SUCCESS = 'tenant/UNIT_LIST_SUCCESS'
export const UNIT_LIST_FAILURE = 'tenant/UNIT_LIST_FAILURE'

export const PROPERTY_UNIT_REQUEST = 'tenant/PROPERTY_UNIT_REQUEST'
export const PROPERTY_UNIT_SUCCESS = 'tenant/PROPERTY_UNIT_SUCCESS'
export const PROPERTY_UNIT_FAILURE = 'tenant/PROPERTY_UNIT_FAILURE'

export const ADD_UNIT_REQUEST = 'tenant/ADD_UNIT_REQUEST'
export const ADD_UNIT_SUCCESS = 'tenant/ADD_UNIT_SUCCESS'
export const ADD_UNIT_FAILURE = 'tenant/ADD_UNIT_FAILURE'

export const UPDATE_UNIT_REQUEST = 'tenant/UPDATE_UNIT_REQUEST'
export const UPDATE_UNIT_SUCCESS = 'tenant/UPDATE_UNIT_SUCCESS'
export const UPDATE_UNIT_FAILURE = 'tenant/UPDATE_UNIT_FAILURE'

export const INVITE_TENANT_REQUEST = 'tenant/INVITE_TENANT_REQUEST'
export const INVITE_TENANT_SUCCESS = 'tenant/INVITE_TENANT_SUCCESS'
export const INVITE_TENANT_FAILURE = 'tenant/INVITE_TENANT_FAILURE'

export const UPDATE_ROOMS_REQUEST = 'tenant/UPDATE_ROOMS_REQUEST'
export const UPDATE_ROOMS_SUCCESS = 'tenant/UPDATE_ROOMS_SUCCESS'
export const UPDATE_ROOMS_FAILURE = 'tenant/UPDATE_ROOMS_FAILURE'

export const RESET_TENANT_REQUEST = 'tenant/RESET_TENANT_REQUEST'
export const RESET_TENANT_SUCCESS = 'tenant/RESET_TENANT_SUCCESS'
export const RESET_TENANT_FAILURE = 'tenant/RESET_TENANT_FAILURE'

export const INPROGRESS_TENANT_REQUEST = 'tenant/INPROGRESS_TENANT_REQUEST'
export const INPROGRESS_TENANT_SUCCESS = 'tenant/INPROGRESS_TENANT_SUCCESS'
export const INPROGRESS_TENANT_FAILURE = 'tenant/INPROGRESS_TENANT_FAILURE'

export const GET_TENANT_BY_INVITE_CODE_REQUEST = 'tenant/GET_TENANT_BY_INVITE_CODE_REQUEST'
export const GET_TENANT_BY_INVITE_CODE_SUCCESS = 'tenant/GET_TENANT_BY_INVITE_CODE_SUCCESS'
export const GET_TENANT_BY_INVITE_CODE_FAILURE = 'tenant/GET_TENANT_BY_INVITE_CODE_FAILURE'

export const GO_TO_TAB = 'tenant/GO_TO_TAB'

export const USER_UPDATE_FIELD_VALUE = 'user/USER_UPDATE_FIELD_VALUE'
