export const PROPERTY_LIST_REQUEST = 'PROPERTY/PROPERTY_LIST_REQUEST'
export const PROPERTY_LIST_SUCCESS = 'PROPERTY/PROPERTY_LIST_SUCCESS'
export const PROPERTY_LIST_FAILURE = 'PROPERTY/PROPERTY_LIST_FAILURE'

export const TRANSFER_PROPERTY_REQUEST = 'PROPERTY/TRANSFER_PROPERTY_REQUEST'
export const TRANSFER_PROPERTY_SUCCESS = 'PROPERTY/TRANSFER_PROPERTY_SUCCESS'
export const TRANSFER_PROPERTY_FAILURE = 'PROPERTY/TRANSFER_PROPERTY_FAILURE'

export const OFFER_LIST_REQUEST = 'PROPERTY/OFFER_LIST_REQUEST'
export const OFFER_LIST_SUCCESS = 'PROPERTY/OFFER_LIST_SUCCESS'
export const OFFER_LIST_FAILURE = 'PROPERTY/OFFER_LIST_FAILURE'

export const CONFIRM_OFFER_REQUEST = 'PROPERTY/CONFIRM_OFFER_REQUEST'
export const CONFIRM_OFFER_SUCCESS = 'PROPERTY/CONFIRM_OFFER_SUCCESS'
export const CONFIRM_OFFER_FAILURE = 'PROPERTY/CONFIRM_OFFER_FAILURE'
