export const PROPERTY_LIST_REQUEST = 'PROPERTY/PROPERTY_LIST_REQUEST'
export const PROPERTY_LIST_SUCCESS = 'PROPERTY/PROPERTY_LIST_SUCCESS'
export const PROPERTY_LIST_FAILURE = 'PROPERTY/PROPERTY_LIST_FAILURE'
